export const RESOURCES_REST_API_PROVIDER = Symbol(
  "RESOURCES_REST_API_PROVIDER"
);
export const RESOURCES_CRYPTO_PROVIDER = Symbol("RESOURCES_CRYPTO_PROVIDER");
export const RESOURCES_TRAY_PROVIDER = Symbol("RESOURCES_TRAY_PROVIDER");
