export const TWO_FACTOR_REST_API_PROVIDER = Symbol(
  "TWO_FACTOR_REST_API_PROVIDER"
);
export const TWO_FACTOR_USER_PROVIDER = Symbol("TWO_FACTOR_USER_PROVIDER");
export const TWO_FACTOR_AUTH_PROVIDER = Symbol("TWO_FACTOR_AUTH_PROVIDER");
